language: php
# list any PHP version you want to test against
php:
# using major version aliases
  - 5.3

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS shimmie;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database shimmie;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database shimmie;" -uroot; fi
  - chmod -R 777 .

script: php tests/simple_test.php -database $DB -url http://127.0.0.1/

# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#travis"
#